name: "Test"

on:
  pull_request:
    types: [opened, synchronize, reopened]

# Only allow one workflow run at a time per PR
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  test:
    name: "Test"
    runs-on: ["ubuntu-latest"]
    env:
      TZ: "Europe/Rome"
    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-node@v6
        name: "Set up Node.js"
        with:
          node-version: 22
          cache: "npm"

      - name: "Test the package"
        run: npm cit --quiet
        timeout-minutes: 5
